version: '3.9'

services:
  postgres_db:
    image: postgres:13
    restart: always
    hostname: postgres
    volumes:
      - "postgres_db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: images_info
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432

  fastapi_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./data:/data

volumes:
  postgres_db: