version: '3.9'

services:
  postgres_db:
    image: postgres:13
    restart: always
    hostname:
      postgres_db
    environment:
#      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    volumes:
      - ./postgres_db/:/var/lib/postgresql/data
    networks:
      backend:

  parser_backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./data:/data
      - .env:/.env
    links:
      - postgres_db
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      backend:

networks:
  backend:
    name: backend