version: '3.9'

services:
  postgres_db:
    image: postgres:13
    restart: always
    hostname:
      postgres_db
    environment:
#      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_db/:/var/lib/postgresql/data

  parser_backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./data:/data
      - .env:/.env
    depends_on:
      - postgres_db